### ISSUE TITLE
how to set DP in llama2 pretrain

### ISSUE THREAD

**Issue by wangqihanginthesky** [aws-neuron/aws-neuron-parallelcluster-samples#21]
This [document](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/general/benchmarks/trn1/trn1-performance.html#training-performance-trn1-trn1n) shows that the best performance in llama2-7B-pretrain is achieved with TP=8, DP=64, and PP=1.
But ,how can I set the DP?

**Comment by aroparasaws** [comment]
DP is set in a way you configure the 3D model parallelism. In our llama7b pretraining script, we set TP=8 and PP=1, DP is calculated by world_size divided by TP and PP. For example - for a 16 node run for trn1.32xlarge nodes, world size is 16*32 = 512, divided by TP * PP i.e 8. So 512/8 is 64, that is DP
