### ISSUE TITLE
training codes

### ISSUE THREAD

**Issue by Abolfazl-kr** [aws-neuron/aws-neuron-parallelcluster-samples#26]
could you please give us full training code for llama2?

**Comment by jyang-aws** [comment]
@Abolfazl-kr 
please refer to the https://github.com/aws-neuron/neuronx-nemo-megatron/tree/main/nemo/examples/nlp/language_modeling for the llama2 example with Nemo.
You can also check out the example with neuronx-distributed: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/libraries/neuronx-distributed/tutorials/training_llama2_tp_pp.html?highlight=llama
